language: node_js

node_js:
  - 14

# 使用 xvfb 来模拟显示 GUI
services:
  - docker
  - xvfb

# 指定要使用的浏览器以及版本
addons:
  chrome: stable
#  hosts:
#    - localhost

#before_install:
#  - echo $TRAVIS_BUILD_DIR/test/data

script:
  - npm i
  - npm run testci
after_script:
  - npm run codecov